openapi: 3.0.3
info:
  title: Football Service
  description: Football Service Backend API Specification
  contact:
    name: API Support
    email: thscorjs1002@naver.com
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: localhost server
tags:
  - name: users
    description: 유저 관련 API
  - name: club
    description: 동호회 관련 API

paths:
  '/users/auth/google':
    get:
      tags:
        - users
      summary: "구글 Oauth 로그인 링크 조회"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: true
              writeOnly: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: true
                writeOnly: true
                properties:
                  link: "https://accounts.google.com/o/oauth2/v2/auth?client_id=436549750929-4pepqro96c8s3sn3a35l84rpeir3brt2.apps.googleusercontent.com&scope=https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&response_type=code&access_type=offline&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fgoogle"
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
